name: Deploy-Wordpress
on:
  push:
jobs:
  deploy:
    runs-on: self-hosted   
    steps:
      - name: Magicking 😀
        shell: bash
        run: |
          sudo chown -R ubuntu:ubuntu /var/www/html/brainstorm
          cd /var/www/html/brainstorm
          sudo git pull
      - name: PHPCS
        shell: bash
        run: |
          cd /var/www/html/brainstorm
          sudo composer phpcs
          sudo chown -R www-data:www-data /var/www/html/brainstorm
